### ISSUE TITLE
Content Removal Request

### ISSUE THREAD

**Issue by Dr34m1ngH1gh** [apksupport/apk.support#34]
Tema APKSupport,

We have been trying use your contact form but this does not work.

![image](https://user-images.githubusercontent.com/106785721/189160493-07c3efa7-835c-4c0b-9668-0a2b73c9cc70.png)

When you try to send the form this never happens.

We would like to request your assistance to remove the following app from your app store. The intellectual develper does not authorize the distribution of their apps on unofficial appstores. 

Thank you in advance. 

Regards.

**Comment by Prakash36987** [comment]
[apksupport.txt](https://github.com/apksupport/apk.support/files/9563292/apksupport.txt)
[apksupport.txt](https://github.com/apksupport/apk.support/files/9563317/apksupport.txt)

Hi Apk.support team,

It is come to our notice that Apk.support platform is being used for pirated apk file distribution and it resulting in huge losses for OTT subscription , theatrical releases. 
We have been sending DMCA notices to delete the APK files belongs to rogue websites and receiving cold response from your end. 
In the light of the above, our clients are taken a serious note of Apk.support non-compliance and insisting us to deindex Apk.support website from search engines and blocking the Apk.support domains across ISP gateways in India.

We request you to comply to our notices to avoid ramifications. Attached file containing APK links for removal

Thanks
Aiplex Support Team
